version: "3.9"

services:
  db:
    image: postgres:latest
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "password"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    container_name: starter-rails
    working_dir: /starter-rails
    volumes:
      - .:/starter-rails
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  dbdata:
  bundle:
